spring:
  application:
    name: booking-service
  #kafka config
  kafka:
    template:
      default-topic: booking
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


  datasource:
    url: jdbc:postgresql://localhost:5434/bookings
    username: ilyasse
    password: ilyasse123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none


inventory:
  service:
    url: http://localhost:8080/api/v1


server:
  port: 8081


eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




